### ISSUE TITLE
Presets from config

### ISSUE THREAD

**Issue by manthey** [girder/large_image#1239]
We have the ability to set configuration files per folder (see https://girder.github.io/large_image/girder_config_options.html#large-image-config-yaml).  When presets are done (#1123), we should then add the ability to set some additional presets in the configuration file.

I think this would have to have some scope about where those presets would apply, as if we are compositing specific channels or bands together then the preset only makes sense if that has those bands or presets.  Maybe something like:
```
imagePresets:
  - name: <preset name>
    frame: ...
    style: ...
    condition: 
      - channels: ['DAPI', 'CD45']
```
where the conditions would all have to match.  The conditions might be a list of channels, a list of bands, a list of axes, the total number of frames, the number of discrete values for specific axes.

We probably would also want to set a default preset (or maybe an order of default presets, since they might not all apply).  And, this default might be something we override for a specific image (add a default to its settings).
