### ISSUE TITLE
Customize item lists

### ISSUE THREAD

**Issue by manthey** [girder/large_image#859]
Currently, item lists can contain thumbnails, macro, and label images based on whether the current user is unset, a regular user, or an admin.  Similarly, images and metadata can be shown in an item page based on this.  Eventually, we want to display columns of metadata in the hierarchy lists, too.

It would be nicer if this could be configured on a per-folder, per-collection, or per-user level.

**Comment by manthey** [comment]
This could be done by fetching a folder-specific config file (that, if no such file is found, would walk up the folder parents until such a file is found).

The file would be named something appropriate like `.large_image_config.yaml` and could contain a variety of settings: e.g.,

```
-
item_page:
  images:
    - macro
access:
  user:
    item_page:
      images:
        - label
        - macro
    item_list:
      images:
        - label
        - macro
      columns:
        - meta.ranking
  admin:
    item_page:
      images:
        - label
        - macro
        - "*"
      metadata:
        - tile
        - internal
```

We probably want a global file specified in settings in case no other config file is found.

Also, should nested config files be merged (or optionally merged)?  It seems like that would be more confusing than useful (and you'd need a debug method to determine why the resultant config is what occurred).

I image that before the hierarchy widget or item page is rendered, we would fetch the config file and then change what gets rendered based on that.
